version: '3'
services:
  web:
    image: node:8.9.4
    ports:
      - 8080:8080
    command: bash -c "npm install && npm run dev"
    working_dir: /src
    volumes:
      -  "C:/Users/higor.freitas/Project/main/corona-vue-free-admin-template-main/template/demo_1:/src"
    environment:
      - CHOKIDAR_USEPOLLING=true